# Configurações de Qualidade para Moransa CI/CD
# Este arquivo define padrões e configurações para verificações automáticas

name: Quality Configuration

# Configurações globais de qualidade
quality_standards:
  backend:
    python_version: "3.10"
    coverage_threshold: 70
    max_complexity: 10
    max_line_length: 127
    security_level: "high"
    
  frontend:
    html_validation: true
    css_max_size: 50000
    accessibility_check: true
    performance_check: true
    
  mobile:
    flutter_version: "3.16.0"
    dart_analysis_level: "strict"
    test_coverage_min: 60
    build_variants: ["debug", "release"]
    
  security:
    secret_scanning: true
    dependency_check: true
    permission_audit: true
    vulnerability_scan: true

# Ferramentas de qualidade utilizadas
tools:
  python:
    - pylint
    - black
    - flake8
    - mypy
    - bandit
    - safety
    - pytest
    
  dart:
    - dart_analyzer
    - dart_format
    - flutter_test
    
  security:
    - bandit
    - safety
    - secret_scanner
    
  general:
    - codecov
    - docker
    - git_hooks

# Configurações de notificação
notifications:
  success:
    - slack_webhook: "${SLACK_WEBHOOK_SUCCESS}"
    - email: "nhadafilipe@gmail.com"
    
  failure:
    - slack_webhook: "${SLACK_WEBHOOK_FAILURE}"
    - email: "nhadafilipe@gmail.com"
    - github_issue: true

# Configurações de artefatos
artifacts:
  retention_days: 30
  types:
    - apk_files
    - coverage_reports
    - security_reports
    - quality_reports
    - docker_images

# Configurações de cache
cache:
  pip_cache: true
  flutter_cache: true
  docker_cache: true
  node_cache: true
  
# Configurações de deploy
deploy:
  environments:
    - development
    - staging
    - production
    
  conditions:
    development:
      branch: "develop"
      auto_deploy: true
      
    staging:
      branch: "main"
      manual_approval: false
      
    production:
      branch: "main"
      manual_approval: true
      tag_required: true